# Generated by Django 6.1.1 on 2026-09-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Used in the course page address, e.g. /services/ui-ux/.', unique=True)),
                ('photo', models.ImageField(blank=True, help_text='WebP, landscape, at least 800px wide.', upload_to='courses/')),
                ('photo_alt', models.CharField(blank=True, help_text='What the photo shows, for screen readers, e.g. "Laptop on a desk beside a notebook".', max_length=150, verbose_name='photo description')),
                ('duration', models.CharField(blank=True, help_text='e.g. "12 weeks". Hidden on the site when empty.', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first. The first six appear on the Home page.')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
