# Generated by Django 6.1.1 on 2026-09-22 01:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Full international number, digits only (country code first, no +). The Enrol buttons open a WhatsApp chat with this number. Left blank, those buttons are hidden.', max_length=20, validators=[django.core.validators.RegexValidator('^\\d{7,15}$', 'Digits only, in full international form, e.g. 2348012345678 — no +, spaces or leading 0.')], verbose_name='WhatsApp number')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
