# Generated by Django 6.1.1 on 2026-09-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(help_text='Keep it short, one or two sentences, so it fits beside the photo.', max_length=300)),
                ('name', models.CharField(help_text='Who said it, shown under the quote.', max_length=100)),
                ('photo', models.ImageField(help_text='WebP, square, at least 300px wide. The face should sit near the centre.', upload_to='testimonials/')),
                ('photo_alt', models.CharField(help_text='What the photo shows, for screen readers, e.g. "Portrait of Ada Obi".', max_length=150, verbose_name='photo description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
