# Generated by Django 6.1.1 on 2026-09-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='photo_alt',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='role',
            field=models.CharField(blank=True, help_text='Shown under the name, e.g. "UI/UX graduate". Hidden on the site when empty.', max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(help_text='WebP, square, at least 300px wide. The face should sit near the centre. Decorative: the name under the quote says who it is.', upload_to='testimonials/'),
        ),
    ]
