# Generated by Django 6.1.1 on 2026-09-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_social_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(help_text='Plain text. Press Enter for a new line.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first. The first question starts open.')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
